import './globals.css';
import { Prompt } from 'next/font/google';

const font = Prompt({
  weight: ['400', '600', '900'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={font.className + ' ' + 'bg-gray-50'}>{children}</body>
    </html>
  );
}
